### ISSUE TITLE
How do we do upsert?

### ISSUE THREAD

**Issue by srikoushik** [dgraph-io/dgraph-js-http#15]
I want to do a query and update a particular predicate.

**Comment by paulftw** [comment]
Here's an older example of upserts: https://github.com/dgraph-io/dgraph-js-http/blob/b14381cb9a21b7379d996d67cc05665aaea52d94/tests/integration/acctUpsert.spec.ts

For questions please use our forums at https://discuss.dgraph.io/

**Comment by paulftw** [comment]
Most modern way to do upsert is using upsert block: 

https://docs.dgraph.io/mutations/#upsert-block

Ratel sends upsert mutations this way:
`client.newTxn().mutate({ mutation: upsertBlockMutation, commitNow: true });`
