### ISSUE TITLE
Browser example : How to bundle the 'dgraph-js-http' lib in an HTML page

### ISSUE THREAD

**Issue by hubyhuby** [dgraph-io/dgraph-js-http#16]
[http1.zip](https://github.com/dgraph-io/dgraph-js-http/files/3832355/http1.zip)

There is an example for Node.js on server side that is working well.
https://github.com/dgraph-io/dgraph-js-http/tree/master/examples/simple

Now when you want to test it on the browser side the require directive is not reconised by the JS on the browser side. " const dgraph = require("dgraph-js-http"); " gives an error.

I manage to use a "bundler " and got to the next series of problems ;) 
Could you please provide with an example ?

This worked a little :
 browserify index-promise.js  > bundle.js

**Comment by hubyhuby** [comment]
![image](https://user-images.githubusercontent.com/26340942/68605410-a48fe080-04ac-11ea-8e66-3eca850acd6c.png)

**Comment by paulftw** [comment]
We have a detailed blog post on this topic: https://blog.dgraph.io/post/building-todo-list-react-dgraph/
