### ISSUE TITLE
Vue component

### ISSUE THREAD

**Issue by ctwhome** [dgraph-io/dgraph-js-http#24]
Similar to <vue-apollo> it would be fantastic to have a <vue-dgraph> component that could run queries and mutations in the same fashion, but with a much cleaning code. 

How hard would it be to wrap this "dgraph-js-http"?

**Comment by paulftw** [comment]
It shouldn't be hard to write a vue wrapper, but I believe that should be done in a separate repository, not here.

`dgraph-js-http` is intended as a minimalistic & framework agnostic JS library.
Vue / React / Angular / other components would be better off implemented on top of this library, not part of it.

**Comment by ctwhome** [comment]
I agree it shouldn't be part of the core of "dgraph-js-http", I am thinking if an official wrapper from you guys would give it continuity and trustability :)
