### ISSUE TITLE
Add a LRU cache for Client

### ISSUE THREAD

**Issue by MichelDiz** [dgraph-io/dgraph-js-http#6]
To reduce the overhead and increase performance.

e.g: http://avoidwork.github.io/tiny-lru/

Or any other in this list https://github.com/dominictarr/bench-lru

**Comment by paulftw** [comment]
Not sure what you want to cache. If you want to cache query/response pairs - this would make querying less predictable and not suitable for all clients (some may need freshest data possible e.g. bank account balance). Users can choose to add this behavior on a higher level.

Closing this feature request for now, let's discuss in Slack if I misunderstood something.
